/**
 * AI 생성 이미지에 "Generated by AI" 워터마크를 추가합니다.
 * @param {string} base64 - 원본 이미지 base64
 * @param {string} mimeType - 이미지 MIME type
 * @returns {Promise<{base64: string, mimeType: string}>}
 */
export const addAiWatermark = (base64, mimeType) => {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.naturalWidth;
            canvas.height = img.naturalHeight;
            const ctx = canvas.getContext('2d');

            // 원본 이미지 그리기
            ctx.drawImage(img, 0, 0);

            // 워터마크 텍스트 설정
            const fontSize = Math.max(12, Math.round(img.naturalWidth * 0.018));
            ctx.font = `${fontSize}px -apple-system, "Segoe UI", sans-serif`;
            ctx.textAlign = 'right';
            ctx.textBaseline = 'bottom';

            // 배경 반투명 박스
            const text = 'Generated by AI';
            const metrics = ctx.measureText(text);
            const padding = fontSize * 0.5;
            const boxX = canvas.width - metrics.width - padding * 3;
            const boxY = canvas.height - fontSize - padding * 2;
            const boxW = metrics.width + padding * 2;
            const boxH = fontSize + padding * 1.5;

            ctx.fillStyle = 'rgba(0, 0, 0, 0.25)';
            ctx.beginPath();
            ctx.roundRect(boxX, boxY, boxW, boxH, fontSize * 0.3);
            ctx.fill();

            // 텍스트
            ctx.fillStyle = 'rgba(255, 255, 255, 0.7)';
            ctx.fillText(text, canvas.width - padding * 2, canvas.height - padding * 0.8);

            const resultBase64 = canvas.toDataURL(mimeType).split(',')[1];
            resolve({ base64: resultBase64, mimeType });
        };
        img.src = `data:${mimeType};base64,${base64}`;
    });
};
